#!/usr/bin/env python3
"""parity_report.py — Generate side-by-side Gazebo vs Isaac Sim trial outcome report.

Reads one JSON per trial-sim combination from exts/aic-dt/docs/trial_outcomes/, groups
by trial_id, compares Gazebo vs Isaac Sim outcomes, writes a deterministic markdown
table to docs/parity-report.md. Exits 0 iff all trials match across sims.

Input file shape (one per trial-sim combination):
    {
      "trial_id":              "trial_1",          # str, matches sample_config.yaml trial keys
      "sim":                   "gazebo" | "isaacsim",
      "insertion_event_fired": true | false,        # bool — did /scoring/insertion_event ever fire
      "offlimit_contact_count": 0,                  # int — total non-empty Contacts msgs on /aic/gazebo/contacts/off_limit
      "completed_steps":        123,                # int — engine-reported step count (-1 if not parseable)
      "ts":                     "2026-05-09T..."   # ISO 8601 of run start
    }

Filename convention: trial_<id>__<sim>.json (double underscore separator).
"""

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_INPUT_DIR = REPO_ROOT / "exts" / "aic-dt" / "docs" / "trial_outcomes"
DEFAULT_OUTPUT = REPO_ROOT / "docs" / "parity-report.md"

REQUIRED_KEYS = ("trial_id", "sim", "insertion_event_fired", "offlimit_contact_count", "completed_steps", "ts")
SUPPORTED_SIMS = ("gazebo", "isaacsim")


def load_outcomes(input_dir: Path):
    """Return {trial_id: {sim: outcome_dict}} sorted deterministically."""
    outcomes: dict[str, dict[str, dict]] = {}
    if not input_dir.is_dir():
        return outcomes
    for path in sorted(input_dir.glob("*.json")):
        with path.open() as f:
            data = json.load(f)
        missing = [k for k in REQUIRED_KEYS if k not in data]
        if missing:
            print(f"WARN: {path.name} missing keys {missing}; skipping", file=sys.stderr)
            continue
        trial_id = data["trial_id"]
        sim = data["sim"]
        if sim not in SUPPORTED_SIMS:
            print(f"WARN: {path.name} has unsupported sim={sim!r}; skipping", file=sys.stderr)
            continue
        outcomes.setdefault(trial_id, {})[sim] = data
    return outcomes


def compare(gz: dict | None, isim: dict | None) -> tuple[bool, str]:
    """Return (match, reason). Match requires both present + identical insertion_event + offlimit."""
    if gz is None or isim is None:
        missing = []
        if gz is None:
            missing.append("gazebo")
        if isim is None:
            missing.append("isaacsim")
        return False, f"missing {','.join(missing)}"
    if gz["insertion_event_fired"] != isim["insertion_event_fired"]:
        return False, f"insertion_event_fired diverges (gz={gz['insertion_event_fired']}, isim={isim['insertion_event_fired']})"
    if gz["offlimit_contact_count"] != isim["offlimit_contact_count"]:
        return False, f"offlimit_contact_count diverges (gz={gz['offlimit_contact_count']}, isim={isim['offlimit_contact_count']})"
    return True, "ok"


def fmt_outcome(o: dict | None) -> str:
    if o is None:
        return "—"
    insertion = "fired" if o["insertion_event_fired"] else "not fired"
    return f"insertion={insertion}, off_limit={o['offlimit_contact_count']}, steps={o['completed_steps']}"


def fmt_bool(b: bool | None) -> str:
    if b is None:
        return "—"
    return "true" if b else "false"


def fmt_int(i: int | None) -> str:
    if i is None:
        return "—"
    return str(i)


def render_markdown(outcomes: dict, all_match: bool) -> str:
    lines = []
    lines.append("# Parity Report — Gazebo vs Isaac Sim trial outcomes")
    lines.append("")
    lines.append("Generated by `exts/aic-dt/scripts/parity_report.py`. Regenerable; do not hand-edit.")
    lines.append("")
    lines.append("| Trial | Gazebo outcome | Isaac Sim outcome | Match? | Insertion event (gz/isim) | Off_limit contacts (gz/isim) | Notes |")
    lines.append("|---|---|---|---|---|---|---|")
    if not outcomes:
        lines.append("| _no trial outcomes captured_ | — | — | — | — | — | run capture scripts first |")
    for trial_id in sorted(outcomes.keys()):
        gz = outcomes[trial_id].get("gazebo")
        isim = outcomes[trial_id].get("isaacsim")
        match, reason = compare(gz, isim)
        lines.append(
            f"| {trial_id} | {fmt_outcome(gz)} | {fmt_outcome(isim)} | "
            f"{'yes' if match else 'no'} | "
            f"{fmt_bool(gz and gz['insertion_event_fired'])}/{fmt_bool(isim and isim['insertion_event_fired'])} | "
            f"{fmt_int(gz and gz['offlimit_contact_count'])}/{fmt_int(isim and isim['offlimit_contact_count'])} | "
            f"{reason} |"
        )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    if not outcomes:
        lines.append("No trial outcomes found. Capture Gazebo + Isaac Sim baselines first.")
    elif all_match:
        lines.append(f"all trials match — {len(outcomes)} trial(s) verified across both sims.")
    else:
        lines.append(f"divergence detected — {len(outcomes)} trial(s) compared; see Match? column for details.")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    p = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--input-dir", type=Path, default=DEFAULT_INPUT_DIR,
                   help=f"Directory of trial_<id>__<sim>.json files (default: {DEFAULT_INPUT_DIR})")
    p.add_argument("--output", type=Path, default=DEFAULT_OUTPUT,
                   help=f"Output markdown path (default: {DEFAULT_OUTPUT})")
    args = p.parse_args()

    outcomes = load_outcomes(args.input_dir)

    if not outcomes:
        print(f"WARN: no trial outcomes found in {args.input_dir}", file=sys.stderr)
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(render_markdown({}, False))
        print("no trials — exit 1", file=sys.stderr)
        return 1

    all_match = True
    for trial_id, by_sim in outcomes.items():
        match, _ = compare(by_sim.get("gazebo"), by_sim.get("isaacsim"))
        if not match:
            all_match = False

    md = render_markdown(outcomes, all_match)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(md)

    if all_match:
        print(f"all trials match across sims ({len(outcomes)} trial(s)). report: {args.output}")
        return 0
    print(f"divergence detected ({len(outcomes)} trial(s) compared). report: {args.output}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
