#!/usr/bin/env python3
# Reference: 04-RESEARCH.md Pitfall 3 + A4; MCP socket pattern from CLAUDE.md
"""probe_taskboard_prim_paths.py — Phase 4 Plan 04-01 Task 2.

Verifies A4 (04-RESEARCH.md line 716, Risks table + Assumptions Log): does the
hardcoded `_PORT_LINK_PATHS` list in
exts/aic-dt/aic_dt/scoring_publishers.py:62-66 cover the live USD prim paths
that the Phase 1 / Phase 4 spawn atoms actually create under
/World/TaskBoard?

Operating model:
  1. Send `quick_start` to a live Isaac Sim aic-dt instance (port 8768).
  2. Issue the spawn atoms that the 3 sample_config.yaml trials exercise:
     spawn_sc_port(0/1, present=True), spawn_nic_card_mount(0..4, present=True),
     spawn_nic_card(present=True).
  3. Traverse the live USD stage via execute_python_code, collect every
     prim path under /World/TaskBoard/ and /World/Objects/.
  4. Compare against the literal _PORT_LINK_PATHS list:
        ["/World/TaskBoard/sc_port_1",
         "/World/TaskBoard/sc_port_2",
         "/World/TaskBoard/nic_card"]
  5. Emit verdict + audit report.

Verdicts:
  PASS                       — all 3 hardcoded paths exist exactly in live list.
  MISMATCH_NIC_CARD_MOUNT    — `nic_card` hardcoded but live tree has only
                               `NICCardMount_<index>` and/or `NICCard`
                               (the Pitfall 3 case).
  MISMATCH_OTHER             — different mismatch shape.

This task does NOT escalate as a blocker. The mismatch is a known risk that
Plan 04-03 owns the fix for via D-13's `set_port_link_paths` MCP atom (or by
having `load_trial` compute the paths from spawn calls dynamically). This
probe just gives 04-03 the verdict to act on.

Pre-requisites:
  - Isaac Sim aic-dt running on localhost:8768
    (verify via: bash <repo-root>/scripts/isaacsim_launch.sh status)
  - DerivedDataCache healthy (verify via:
    ~/env_isaaclab/bin/python <repo-root>/scripts/prime_usd_cache.py status)

Usage:
  ~/env_isaaclab/bin/python exts/aic-dt/scripts/probe_taskboard_prim_paths.py
"""
import json
import os
import socket
import sys
import time

# --- Constants -------------------------------------------------------------

MCP_HOST = "127.0.0.1"
MCP_PORT = 8768

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
REPORT_PATH = os.path.join(REPO_ROOT, ".planning/phases/04-trial-loader/taskboard_prim_paths.txt")

# Source of truth for what scoring_publishers.py expects (Phase 3 hardcode).
# Mirrored verbatim from exts/aic-dt/aic_dt/scoring_publishers.py:62-66.
_PORT_LINK_PATHS = [
    "/World/TaskBoard/sc_port_1",
    "/World/TaskBoard/sc_port_2",
    "/World/TaskBoard/nic_card",
]


# --- MCP helper (verbatim from CLAUDE.md) ----------------------------------

def mcp_send(host: str, port: int, type_: str, params: dict, timeout_s: float = 120) -> dict:
    """Send a single JSON-encoded MCP command and recv-until-parse.

    No length prefix, no newline framing — server `json.loads` until it
    parses successfully (CLAUDE.md MCP socket protocol section).
    """
    s = socket.socket()
    s.settimeout(timeout_s)
    s.connect((host, port))
    try:
        s.sendall(json.dumps({"type": type_, "params": params}).encode())
        buf = b""
        while True:
            chunk = s.recv(16384)
            if not chunk:
                break
            buf += chunk
            try:
                return json.loads(buf.decode())
            except json.JSONDecodeError:
                continue
        raise RuntimeError("MCP socket closed before complete JSON response")
    finally:
        s.close()


# --- Main probe flow -------------------------------------------------------

def main() -> int:
    report_lines = []

    def log(line: str = ""):
        print(line)
        report_lines.append(line)

    log(f"# Generated by probe_taskboard_prim_paths.py on {time.strftime('%Y-%m-%dT%H:%M:%S%z')}")
    log("# Phase 4 Plan 04-01 Task 2 — A4 prim-path probe")
    log("# Plan: .planning/phases/04-trial-loader/04-01-PLAN.md")
    log()

    # Step 1: quick_start (idempotent — completes in ~5s on warm cache).
    log("## Step 1: quick_start")
    try:
        resp = mcp_send(MCP_HOST, MCP_PORT, "quick_start", {})
        log(f"  status={resp.get('status') or resp.get('result', {}).get('status')}")
        msg = resp.get("result", {}).get("message", "") if isinstance(resp.get("result"), dict) else ""
        log(f"  message={msg}")
    except Exception as e:
        log(f"  FAILED: {type(e).__name__}: {e}")
        log()
        log("=== A4 VERDICT: FAIL_MCP_SOCKET ===")
        _write_report(report_lines)
        print("A4 VERDICT: FAIL_MCP_SOCKET — see " + REPORT_PATH, file=sys.stderr)
        return 1
    log()

    # Step 2: issue the spawn permutations the 3 sample trials exercise.
    log("## Step 2: spawn atoms (trials 1/2/3 union)")
    spawn_calls = [
        ("spawn_sc_port", {"index": 0, "present": True}),
        ("spawn_sc_port", {"index": 1, "present": True}),
        ("spawn_nic_card_mount", {"index": 0, "present": True}),
        ("spawn_nic_card_mount", {"index": 1, "present": True}),
        ("spawn_nic_card_mount", {"index": 2, "present": True}),
        ("spawn_nic_card_mount", {"index": 3, "present": True}),
        ("spawn_nic_card_mount", {"index": 4, "present": True}),
        ("spawn_nic_card", {"present": True}),
    ]
    for atom, params in spawn_calls:
        try:
            r = mcp_send(MCP_HOST, MCP_PORT, atom, params)
            outer = r.get("status", "?")
            inner = (r.get("result") or {}).get("status", "?") if isinstance(r.get("result"), dict) else "?"
            inner_msg = (r.get("result") or {}).get("message", "") if isinstance(r.get("result"), dict) else ""
            log(f"  {atom}({params}) -> outer={outer} inner={inner} msg={inner_msg!r}")
        except Exception as e:
            log(f"  {atom}({params}) -> FAILED: {type(e).__name__}: {e}")
    log()

    # Step 3: traverse stage and collect prim paths under /World/TaskBoard/* and /World/Objects/*.
    log("## Step 3: live USD traversal (stage.Traverse)")
    probe_code = (
        "import omni.usd\n"
        "stage = omni.usd.get_context().get_stage()\n"
        "lines = []\n"
        "for prim in stage.Traverse():\n"
        "    p = str(prim.GetPath())\n"
        "    if p.startswith('/World/TaskBoard') or p.startswith('/World/Objects'):\n"
        "        ty = prim.GetTypeName()\n"
        "        lines.append(f'{p}\\t{ty}')\n"
        "result = '\\n'.join(sorted(lines))\n"
    )
    try:
        r = mcp_send(MCP_HOST, MCP_PORT, "execute_python_code", {"code": probe_code})
        # _cmd_execute_python_code returns {"status","message","output","result"}
        # at the top level; older format may wrap under .result. Handle both.
        live_text = ""
        if isinstance(r.get("result"), str):
            live_text = r["result"]
        elif isinstance(r.get("result"), dict):
            inner = r["result"]
            live_text = inner.get("result") or inner.get("output") or ""
        else:
            live_text = r.get("output") or ""
        if not live_text:
            log(f"  WARNING: empty traversal output. raw response keys: {list(r.keys())}")
            live_text = ""
    except Exception as e:
        log(f"  FAILED: {type(e).__name__}: {e}")
        log()
        log("=== A4 VERDICT: FAIL_STAGE_TRAVERSE ===")
        _write_report(report_lines)
        return 1
    log()

    # Step 4: enumerate live paths.
    live_paths = []
    for line in live_text.splitlines():
        line = line.strip()
        if not line:
            continue
        if "\t" in line:
            path, ty = line.split("\t", 1)
        else:
            path, ty = line, ""
        live_paths.append((path, ty))

    log("## Live /World/TaskBoard/* prim paths after spawn cycle")
    if not live_paths:
        log("  (empty — see WARNING above)")
    else:
        for path, ty in live_paths:
            log(f"  {path}  [{ty}]")
    log()

    # Step 5: compare _PORT_LINK_PATHS against live tree.
    live_set = {p for p, _ in live_paths}

    log("## _PORT_LINK_PATHS audit")
    log("| hardcoded path | match? | implication |")
    log("|---|---|---|")
    matches = []
    for hp in _PORT_LINK_PATHS:
        match = hp in live_set
        matches.append(match)
        if match:
            implication = "OK — scoring contact subscription will tag this prim"
        else:
            # Look for spiritual matches under /World/TaskBoard/ or /World/Objects/.
            tail = hp.rsplit("/", 1)[-1]
            similar = [p for p in live_set if tail.lower() in p.lower() or p.lower().endswith("/" + tail.lower())]
            similar_strs = [s.split("/")[-1] for s in similar]
            implication = f"MISMATCH — closest live: {similar_strs}" if similar else "MISMATCH — nothing similar in live tree"
        log(f"| `{hp}` | {'PASS' if match else 'MISMATCH'} | {implication} |")
    log()

    # Step 6: classify verdict.
    if all(matches):
        verdict = "PASS"
    else:
        # The Pitfall 3 signature: nic_card is hardcoded but live tree has
        # NICCardMount_<i> and/or NICCard, neither of which equals nic_card.
        nic_card_hardcoded_missing = "/World/TaskBoard/nic_card" not in live_set
        any_nic_card_mount_live = any("NICCardMount" in p for p in live_set)
        any_NICCard_live = any(p.endswith("/NICCard") for p in live_set)
        if nic_card_hardcoded_missing and (any_nic_card_mount_live or any_NICCard_live):
            verdict = "MISMATCH_NIC_CARD_MOUNT"
        else:
            verdict = "MISMATCH_OTHER"

    if verdict != "PASS":
        log("## RECOMMENDATION FOR PLAN 04-03")
        log()
        log("A4 verdict is " + verdict + " — Plan 04-03's `load_trial` MUST")
        log("either:")
        log("  (a) Add a `set_port_link_paths(paths: list[str])` setter on")
        log("      `AicScoringPublishers` (D-13 fallback path) AND have")
        log("      `load_trial` compute port paths from spawn-atom call sites")
        log("      (e.g. `/World/TaskBoard/SCPort_<index>` for sc_port and")
        log("      `/World/TaskBoard/NICCardMount_<index>` for nic_card_mount),")
        log("      passing them to `_start_aic_scoring_publishers()`.")
        log("  (b) Rename the spawn atoms' prim paths to match the hardcoded")
        log("      list (lossy — breaks parity with spawn_task_board.launch.py")
        log("      naming convention). NOT recommended.")
        log()
        log("Recommended: option (a). The setter is a 1-surface addition (no")
        log("MCP atom needed — it's a public method on the publisher class")
        log("called from `_start_aic_scoring_publishers()`).")
        log()
        log("Live spawn paths to feed into the setter (extracted from this run):")
        for p in sorted(live_set):
            if any(token in p for token in ("SCPort_", "NICCard", "TaskBoard/sc_port", "TaskBoard/nic_card")):
                log(f"  - {p}")
        log()

    log("=== A4 VERDICT: " + verdict + " ===")

    _write_report(report_lines)

    # One-line stdout verdict for the plan acceptance gate.
    print(f"A4 VERDICT: {verdict} — see {REPORT_PATH}")
    return 0


def _write_report(lines):
    os.makedirs(os.path.dirname(REPORT_PATH), exist_ok=True)
    with open(REPORT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[probe] Report written: {REPORT_PATH}")


if __name__ == "__main__":
    sys.exit(main())
