#!/usr/bin/env bash
# Reference: 04-RESEARCH.md Q4 + A2; mirrors snapshot_aic_eval_offlimit.sh pattern
# scripts/verify_kilted_humble_interop.sh — Phase 4 Plan 04-01 Task 1.
#
# Smoke test for A2 (04-RESEARCH.md line 715, Risks table): does ros-kilted
# (aic_eval container) ↔ ros-humble (Isaac Sim bridge) RMW interop hold for
# the AIC msg packages we care about (sensor_msgs/JointState +
# aic_control_interfaces/JointMotionUpdate)?
#
# Test design:
#   1. Start aic_eval headless with start_aic_engine:=true so /joint_states
#      and /aic_controller/joint_commands publishers come up. Override
#      RMW_IMPLEMENTATION + ROS_DOMAIN_ID on the container side to match
#      what the Phase 4 Plan 04-03 wrapper will set.
#   2. From host humble env (~/env_isaaclab venv), subscribe to /joint_states
#      via rclpy and decode one message. PASS = JointState fields populated.
#   3. From host, look up topic type for /aic_controller/joint_commands.
#      PASS = type resolves to aic_control_interfaces/msg/JointMotionUpdate
#      (NOT '<UNKNOWN>'); the host-side rosidl typesupport for the kilted-built
#      ABI loads cleanly.
#   4. Tear down container.
#
# NOTE on host ros2 CLI: env_isaaclab's /install/bin/ros2 binary has a
# Python 3.10/3.11 shebang mismatch + missing netifaces — the CLI is broken in
# the current venv. We work around by writing a tiny rclpy harness inline that
# does subscribe + topic-info type resolution directly through the Python API.
# This is also what `ros2 topic echo` does internally; just bypassing the CLI
# entry-point bug.
#
# Usage:
#   bash exts/aic-dt/scripts/verify_kilted_humble_interop.sh
#
# Output:
#   .planning/phases/04-trial-loader/kilted_humble_interop.txt with final
#   line "=== A2 VERDICT: <PASS|FAIL_RMW_OVERRIDE|FAIL_CUSTOM_MSG_ABI|FAIL_OTHER> ==="
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
REPORT="$REPO_ROOT/.planning/phases/04-trial-loader/kilted_humble_interop.txt"
mkdir -p "$(dirname "$REPORT")"

EVAL_CONTAINER="aic_eval"
# Per Phase 1 D-14: pinned digest sha256:be08f28709acc4662da7378e94c5efccb66a8a0fff27ffccdc68e471d8967433
EVAL_IMAGE_PIN="ghcr.io/intrinsic-dev/aic/aic_eval@sha256:be08f28709acc4662da7378e94c5efccb66a8a0fff27ffccdc68e471d8967433"
EVAL_IMAGE_TAG="ghcr.io/intrinsic-dev/aic/aic_eval:latest"

# Initialize report (overwrite on each run).
{
  echo "# Generated by verify_kilted_humble_interop.sh on $(date -Iseconds)"
  echo "# Phase 4 Plan 04-01 Task 1 — A2 RMW interop smoke (kilted ↔ humble)"
  echo "# Plan: .planning/phases/04-trial-loader/04-01-PLAN.md"
  echo ""
} > "$REPORT"

cleanup() {
  echo "Tearing down aic_eval..." | tee -a "$REPORT"
  docker stop "$EVAL_CONTAINER" 2>/dev/null || true
  docker rm "$EVAL_CONTAINER" 2>/dev/null || true
}
trap cleanup EXIT

# Step 0: idempotent cleanup of any prior state
docker rm -f "$EVAL_CONTAINER" 2>/dev/null || true

# Step 1: bring up aic_eval with override env so it speaks fastrtps on domain 7.
# This matches what Plan 04-03's wrapper will configure for the engine container.
echo "## Step 1: aic_eval bringup (RMW_IMPLEMENTATION=rmw_fastrtps_cpp, ROS_DOMAIN_ID=7)" | tee -a "$REPORT"
echo "Starting container with image $EVAL_IMAGE_PIN ..." | tee -a "$REPORT"
if ! docker run -d --name "$EVAL_CONTAINER" --gpus all --runtime=nvidia \
    -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=all \
    --net=host --privileged \
    -e DISPLAY="${DISPLAY:-:0}" \
    -e ROS_DOMAIN_ID=7 \
    -e RMW_IMPLEMENTATION=rmw_fastrtps_cpp \
    "$EVAL_IMAGE_PIN" \
    ground_truth:=true start_aic_engine:=true gazebo_gui:=false 2>&1 | tee -a "$REPORT"; then
  # Fallback to tag if pinned digest is unavailable locally (e.g. fresh pull required)
  echo "Pinned digest run failed; retrying with :latest tag..." | tee -a "$REPORT"
  docker run -d --name "$EVAL_CONTAINER" --gpus all --runtime=nvidia \
    -e NVIDIA_VISIBLE_DEVICES=all -e NVIDIA_DRIVER_CAPABILITIES=all \
    --net=host --privileged \
    -e DISPLAY="${DISPLAY:-:0}" \
    -e ROS_DOMAIN_ID=7 \
    -e RMW_IMPLEMENTATION=rmw_fastrtps_cpp \
    "$EVAL_IMAGE_TAG" \
    ground_truth:=true start_aic_engine:=true gazebo_gui:=false 2>&1 | tee -a "$REPORT"
fi

echo "Sleeping 35s for Gazebo + controllers + aic_engine startup..." | tee -a "$REPORT"
sleep 35
echo "" >> "$REPORT"

# Step 2: confirm container side is healthy and publishing the topics we care about.
echo "## Step 2: container-side topic surface sanity check" | tee -a "$REPORT"
docker exec "$EVAL_CONTAINER" bash -c '
  source /opt/ros/kilted/setup.bash &&
  export RMW_IMPLEMENTATION=rmw_fastrtps_cpp &&
  export ROS_DOMAIN_ID=7 &&
  ros2 daemon stop 2>/dev/null; sleep 1 &&
  timeout 8 ros2 topic list 2>&1 | grep -E "/joint_states|/aic_controller/joint_commands|/scoring/insertion_event" | sort
' 2>&1 | tee -a "$REPORT" || true
echo "" >> "$REPORT"

# Step 3: host-side decode test via inline rclpy harness.
# The env_isaaclab venv defaults to RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
# (per ~/env_isaaclab/bin/activate); we explicitly override to fastrtps to
# match the container side. ROS_DOMAIN_ID=7 isolation per CLAUDE.md.
echo "## Step 3: host humble decode of /joint_states via rclpy" | tee -a "$REPORT"

JS_DECODE_OUT="$(mktemp)"
JS_DECODE_RC=0
bash -c '
  source ~/env_isaaclab/bin/activate
  export ROS_DOMAIN_ID=7
  export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
  python - <<PYEOF
import sys
import time
import rclpy
from rclpy.node import Node
from sensor_msgs.msg import JointState

class OneShot(Node):
    def __init__(self):
        super().__init__("verify_kilted_humble_interop")
        self.msg = None
        self.create_subscription(JointState, "/joint_states", self._cb, 10)
    def _cb(self, msg):
        self.msg = msg

rclpy.init()
node = OneShot()
deadline = time.time() + 15.0
while time.time() < deadline and node.msg is None:
    rclpy.spin_once(node, timeout_sec=0.5)

if node.msg is None:
    print("DECODE_FAIL: no message received within 15s")
    sys.exit(1)

m = node.msg
print(f"DECODE_OK: header.stamp={m.header.stamp.sec}.{m.header.stamp.nanosec:09d}")
print(f"DECODE_OK: name=({len(m.name)}) {list(m.name)[:8]}")
print(f"DECODE_OK: position=({len(m.position)}) {[round(p,4) for p in list(m.position)[:8]]}")
node.destroy_node()
rclpy.shutdown()
sys.exit(0)
PYEOF
' > "$JS_DECODE_OUT" 2>&1 || JS_DECODE_RC=$?

cat "$JS_DECODE_OUT" | tee -a "$REPORT"
echo "" >> "$REPORT"

# Step 4: custom-msg ABI resolution test — try to import + introspect the type.
# This catches the rosidl_typesupport_c failure pattern seen in Phase 1 (the
# Python 3.10 vs 3.11 ABI mismatch). For the JointMotionUpdate package built
# in env_isaaclab's humble workspace.
echo "## Step 4: host humble import + type-resolve of aic_control_interfaces/msg/JointMotionUpdate" | tee -a "$REPORT"

JMU_OUT="$(mktemp)"
JMU_RC=0
bash -c '
  source ~/env_isaaclab/bin/activate
  export ROS_DOMAIN_ID=7
  export RMW_IMPLEMENTATION=rmw_fastrtps_cpp
  python - <<PYEOF
import sys
try:
    from aic_control_interfaces.msg import JointMotionUpdate
    print("IMPORT_OK: aic_control_interfaces.msg.JointMotionUpdate imported cleanly")
    # Check the rosidl typesupport actually loads (the failure mode is at
    # subscription-creation time, not at import time, so we go further)
    import rclpy
    from rclpy.node import Node
    rclpy.init()
    node = rclpy.create_node("verify_jmu_typesupport")
    sub = node.create_subscription(
        JointMotionUpdate, "/aic_controller/joint_commands", lambda m: None, 10)
    print("TYPESUPPORT_OK: subscription created — rosidl_typesupport_c loaded the kilted-built ABI")
    node.destroy_node()
    rclpy.shutdown()
    sys.exit(0)
except Exception as e:
    print(f"TYPESUPPORT_FAIL: {type(e).__name__}: {e}")
    import traceback
    traceback.print_exc()
    sys.exit(1)
PYEOF
' > "$JMU_OUT" 2>&1 || JMU_RC=$?

cat "$JMU_OUT" | tee -a "$REPORT"
echo "" >> "$REPORT"

# Step 5: aggregate verdict.
echo "## Final verdict" | tee -a "$REPORT"
VERDICT="FAIL_OTHER"
if grep -q "DECODE_OK" "$JS_DECODE_OUT" && grep -q "TYPESUPPORT_OK" "$JMU_OUT"; then
  VERDICT="PASS"
elif ! grep -q "DECODE_OK" "$JS_DECODE_OUT"; then
  VERDICT="FAIL_RMW_OVERRIDE"
elif ! grep -q "TYPESUPPORT_OK" "$JMU_OUT"; then
  VERDICT="FAIL_CUSTOM_MSG_ABI"
fi

if [[ "$VERDICT" != "PASS" ]]; then
  {
    echo ""
    echo "## BLOCKER ESCALATION"
    echo ""
    echo "A2 verdict is $VERDICT — Plan 04-03 cannot proceed with the assumption"
    echo "that the stock aic_eval image works on humble + fastrtps + domain 7."
    echo ""
    echo "Recommended next step:"
    case "$VERDICT" in
      FAIL_RMW_OVERRIDE)
        echo "  - The container ignores or misconfigures RMW_IMPLEMENTATION/ROS_DOMAIN_ID overrides."
        echo "  - Inspect docker/aic_eval/Dockerfile (\$HOME/Documents/aic/docker/aic_eval/Dockerfile)"
        echo "    for hard-coded zenoh router config; build derived my-eval-isaac:v1 with humble base"
        echo "    + fastrtps default (Plan 04-03 Sub-A path). Adds ~30 min of build time."
        ;;
      FAIL_CUSTOM_MSG_ABI)
        echo "  - sensor_msgs/JointState decoded fine but the kilted-built aic_control_interfaces"
        echo "    typesupport will not load against humble's rosidl_typesupport_c."
        echo "  - Plan 04-03 must build aic_control_interfaces from source against humble (we"
        echo "    already do this in env_isaaclab — verify the workspace is current via"
        echo "    exts/aic-dt/scripts/build_aic_msgs.sh)."
        ;;
      *)
        echo "  - Inspect the report sections above for the actual failure mode."
        ;;
    esac
    echo ""
    echo "Until A2 is PASS, Plan 04-02 / 04-03 / 04-04 / 04-05 are blocked."
  } | tee -a "$REPORT"
fi

echo "" | tee -a "$REPORT"
echo "=== A2 VERDICT: ${VERDICT} ===" | tee -a "$REPORT"

# Cleanup tmp files
rm -f "$JS_DECODE_OUT" "$JMU_OUT"

# Exit code: 0 on PASS, 1 on FAIL — caller (the executor) decides what to do
# with the verdict (escalate via HANDOFF.json + .user_pause if non-PASS per
# the autonomous-mode contract in CLAUDE.md).
if [[ "$VERDICT" == "PASS" ]]; then
  exit 0
else
  exit 1
fi
